sequenceDiagram
    participant Client
    participant Server

    Client->>Server: (1) GET /resource
    Server--xClient: (2) 402 Payment Required<br/>WWW-Authenticate: Payment <challenge>
    Note right of Client: (3) Client fulfills payment challenge<br/>(signs transaction, pays invoice, etc.)
    Client->>Server: (4) GET /resource<br/>Authorization: Payment <credential>
    Note left of Server: (5) Server verifies and settles
    Server-->>Client: (6) 200 OK<br/>Payment-Receipt: <receipt>
